# this is for supertux
SET(SUPERTUX_VERSION_MAJOR 0)
SET(SUPERTUX_VERSION_MINOR 6)
SET(SUPERTUX_VERSION_PATCH 3)
SET(SUPERTUX_VERSION_TWEAK )
SET(SUPERTUX_VERSION_STRING v0.6.3-876-g07bd100c3)
SET(SUPERTUX_VERSION_BUILD 876)
